site_name: Flexygo Core
site_author: Flexygo
copyright: Copyright © 2025 Flexygo
theme:
  favicon: images/logos/favicon.png
  logo: images/logos/logo.png
  name: material
  language: es
  palette:
  - scheme: slate
    primary: black
    accent: custom
    toggle:
        icon: material/brightness-4
        name: Switch to light mode
  - scheme: default
    toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    primary: black
    accent: custom
  features:
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css
  - stylesheets/center-images.css
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/flexygo
      name: Flexygo Discord
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/flexygo
      name: Flexygo Instagram
  generator: false
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search:
      lang: es
  - glightbox
nav:
  - Inicio: index.md
  - Despliegue:
      - Instalador: 
        - Introducción: despliegue/instalador.md
        - Instalación básica: despliegue/instalacionbasica.md
        - Instalación avanzada: despliegue/instalacionavanzada.md
        - Instalación Docker (WIP): despliegue/instalaciondocker.md
      - Actualizador:
        - Flujo actualización: despliegue/actualizador.md
        - Docker: despliegue/actualizadordocker.md
      - Kestrel: despliegue/kestrel.md
      - IIS: despliegue/iis.md
      - Docker: despliegue/docker.md
  - Crear Producto:
      - Requisitos previos: producto/requisitos.md
      - Plantilla: producto/plantilla.md
      - Gestión producto: producto/gestionproducto.md
      - Extensión Visual Studio: producto/extension.md
  - CI/CD:
      - Visión general: cicd/overview.md
      - TeamCity: cicd/teamcity.md
      - GitHub/GitLab : cicd/github-gitlab.md
      - Azure DevOps: cicd/azure-devops.md
